import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const INCLUDE_RE = /<!--\s*@include\s+([^\s]+)\s*-->/g;
const GENERATED_BANNER = '<!-- generated by build-ui; edit index.src.html -->\n';

export function collectDuplicateIds(html) {
  const ids = [];
  const re = /\bid=["']([^"']+)["']/g;
  let m;
  while ((m = re.exec(html))) ids.push(m[1]);
  const seen = new Set();
  const dupes = [];
  for (const id of ids) {
    if (seen.has(id)) dupes.push(id);
    seen.add(id);
  }
  return dupes;
}

export function buildUi(srcPath) {
  const absSrc = path.resolve(srcPath);

  function expand(fileAbs, stack) {
    if (stack.includes(fileAbs)) {
      throw new Error(`include cycle: ${fileAbs}`);
    }
    if (!fs.existsSync(fileAbs)) {
      throw new Error(`include not found: ${path.basename(fileAbs)}`);
    }
    const nextStack = [...stack, fileAbs];
    const baseDir = path.dirname(fileAbs);
    const raw = fs.readFileSync(fileAbs, 'utf8');
    return raw.replace(INCLUDE_RE, (_, inc) => {
      return expand(path.resolve(baseDir, inc), nextStack);
    });
  }

  const content = expand(absSrc, []);
  const dupes = collectDuplicateIds(content);
  if (dupes.length) {
    throw new Error(`duplicate id attributes: ${dupes.join(', ')}`);
  }
  return GENERATED_BANNER + content;
}

/** Keep packaged `/min-version.json` identical to the repo-root policy file. */
export function syncMinVersionPolicy(rootDir = process.cwd(), { check = false } = {}) {
  const src = path.join(rootDir, 'min-version.json');
  const dest = path.join(rootDir, 'public', 'min-version.json');
  if (!fs.existsSync(src)) {
    throw new Error('missing min-version.json at repo root');
  }
  const next = fs.readFileSync(src, 'utf8');
  if (check) {
    const onDisk = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : '';
    if (onDisk !== next) {
      throw new Error('public/min-version.json out of date; run npm run build:ui');
    }
    return { changed: false };
  }
  const prev = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : null;
  if (prev === next) return { changed: false };
  fs.writeFileSync(dest, next);
  return { changed: true };
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const check = process.argv.includes('--check');
  const publicDir = path.join(process.cwd(), 'public');
  const src = path.join(publicDir, 'index.src.html');
  const dest = path.join(publicDir, 'index.html');
  if (!fs.existsSync(src)) {
    console.error('missing public/index.src.html');
    process.exit(1);
  }
  try {
    syncMinVersionPolicy(process.cwd(), { check });
  } catch (err) {
    console.error(err && err.message ? err.message : err);
    process.exit(1);
  }
  const built = buildUi(src);
  if (check) {
    const onDisk = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : '';
    if (onDisk !== built) {
      console.error('index.html out of date; run npm run build:ui');
      process.exit(1);
    }
    process.exit(0);
  }
  fs.writeFileSync(dest, built);
  console.log('wrote public/index.html');
  console.log('synced public/min-version.json');
}
