'use strict';

const { loadDocxTemplate, packDocxBuffer } = require('./shared.js');
const { fillNoteDocumentXml } = require('./note-xml-fill.js');

const ORIG_INTERR =
  'PACIENTE FEMENINA DE 77 AÑOS CON ANTECEDENTES DE DM2 E HTA, INTERCONSULTADA A MEDICINA INTERNA EL 03/04/26 POR DESCONTROL HIPERTENSIVO EN CONTEXTO DE HOSPITALIZACIÓN POR ABSCESO HEPÁTICO EN LÓBULO IZQUIERDO DE 153 CC (CON ANTECEDENTE DE LAPAROTOMÍA EXPLORATORIA CON DRENAJE DE ABSCESO Y APENDICECTOMÍA EL 13/03/26 EN CHARCAS, SLP, Y POSTERIOR DRENAJE PERCUTÁNEO CON KIT UNIVERSAL 10 FR EL 01/04/26). DURANTE SU SEGUIMIENTO SE HA LOGRADO MEJOR CONTROL TENSIONAL, ENCONTRÁNDOSE HOY CON TA DE 130/70 MMHG. SE DOCUMENTÓ HIPOKALEMIA PERSISTENTE (NADIR 3.1) CON REPOSICIONES SERIADAS DE POTASIO Y MAGNESIO, PENDIENTE AÚN ABORDAJE COMPLETO CON ELECTROLITOS URINARIOS Y GASES VENOSOS. PRESENTA EDEMA GODET ++ SIN HABERSE COLOCADO VENDAJE COMPRESIVO NI SONDA FOLEY A PESAR DE SUGERENCIAS REITERADAS. SIN POSIBILIDAD DE VALORAR RETO CON FUROSEMIDA A PESAR DE SU SUGERENCIA. LA TAC ABDOMINAL CONTRASTADA PARA VALORAR EVOLUCIÓN DE LA COLECCIÓN Y POSICIÓN DEL DRENAJE BLAKE CONTINÚA PENDIENTE A PESAR DE MULTIPLES SUGERENCIAS. SE MODIFICÓ ESQUEMA ANTIBIÓTICO A ERTAPENEM POR INDICACION DE SERVICIO DE INFECTOLOGIA. LAS GLUCOMETRÍAS SE HAN MANTENIDO PARCIALMENTE FUERA DE META CON AJUSTE DE RESCATES DE INSULINA. DEBIDO A LO ANTERIOR SE DECIDE ALTA POR PARTE DE MEDICINA INTERNA DE MANERA INTRAHOSPITALARIA. EN CASO DE PERSISTENCIA DE ALTERACION ELECTROLITICA, FALLA A CONTROL DE TENSION ARTERIAL, SE RECOMIENDA INTERCONSULTAR A EQUIPO DE GUARDIA. ';

const ORIG_EVOL_LINES = [
  'N: FOUR 16/16 PUNTOS, SIN DATOS DE FOCALIZACIÓN, ORIENTADO EN 3 ESFERAS, ALERTA || ANALGESIA CON PARACETAMOL 1 GRAMO EN CASO DE DOLOR LEVE O FIEBRE',
  'V: FR 19 RPM, SATO2 97% AL AIRE AMBIENTE | SIN DATOS DE DIFICULTAD RESPIRATORIA || CAMPOS PULMONARES BIEN VENTILADOS',
  'HD: ESTABLE, TA 130/70 MMHG, FC 72 LPM || SIN VASOPRESORES',
  'HI: AFEBRIL, TEMPERATURA 36°C || ANTIBIÓTICOS: ERTAPENEM 1 G IV CADA 24 HORAS (DÍA 1 FUNCIONAL — METRONIDAZOL Y TRIMETOPRIM/SULFAMETOXAZOL SUSPENDIDOS)',
  'NM: DIETA BLANDA DIABÉTICA || INGRESOS 1100 CC, 3 DIURESIS ESPONTÁNEAS, BALANCE NC || DRENAJE UNIVERSAL (BLAKE): 0 CC || GLUCOMETRÍAS CAPILARES (194, 114, 168 MG/DL)',
];

const ORIG_ESTUDIOS_LINES = [
  '07.04.26',
  'Glu  Cr 0.4 BUN 9    AU 2.3  COL 171',
  'Na 137.7 Cl 101.2 K 3.3 Ca 8.1 F 3.7 Mg 1.63',
  '06.04.26',
  'Hb 11.4 Hto 34.8 VCM 86 HCM 28.2 Leu 4.92 Neu 2.76 Eos 0.275 Plt 198   ',
  'Glu 190 Cr 0.4 BUN 8 PCR 0.3   AU 2.6 TGL 153 COL 166',
  'Na 139.8 Cl 105 K 3.2 Ca 7.9 F 3.4 ',
  'Alb 2.5 AST 11 ALT 6 FA 103 BT 0.3 BD 0.1 BI 0.2 LDH 120 Amil 25',
];

const ORIG_MEDICO_SUFFIX =
  'MI KARLA PAOLA MONCADA, R3MI ALEXANDRA MAGAÑA, R2MI PAULINA GARCIA, R1MI MAURICIO SALAS,';

const TX_LEFT_ORIG = [
  '2.____________________________________',
  '3.____________________________________',
  '4.____________________________________',
  '5.____________________________________',
];

const TX_RIGHT_ORIG = [
  '7.   _______________________________________',
  '8.   _______________________________________',
  '9.   _______________________________________',
  '10._______________________________________',
];

async function generateNoteBuffer({ patient, note }) {
  patient = patient || {};
  note = note || {};

  const { names, files } = await loadDocxTemplate('template.docx');
  const xml = fillNoteDocumentXml(
    files['word/document.xml'].toString('utf-8'),
    patient,
    note,
    {
      ORIG_INTERR,
      ORIG_EVOL_LINES,
      ORIG_ESTUDIOS_LINES,
      TX_LEFT_ORIG,
      TX_RIGHT_ORIG,
      ORIG_MEDICO_SUFFIX,
    },
  );

  files['word/document.xml'] = Buffer.from(xml, 'utf-8');
  return packDocxBuffer(files, names);
}

module.exports = {
  generateNoteBuffer,
  ORIG_INTERR,
  ORIG_EVOL_LINES,
};
